### ISSUE TITLE
Clarification about custom fonts

### ISSUE THREAD

**Issue by korya** [jung-kurt/gofpdf#1]
I'm not sure how I can add and use custom fonts:
  - why is the font `.ttf` file not enough?
  - where do I get a `.map` file for my font?
  - how to export the font so it will be "unicode-compatible"?

I'm interested in using `DejaVuSansCondensed.ttf` from Dejavu font distribution.

PS: the project is awesome! you've done a great work!

**Comment by korya** [comment]
OK. I'm an idiot.

I found the`.map` files in `font/` dir (surprisingly).

Is there a good way to support unicode? Any workaround to work with chinese, cyrrilic, hebrew fonts?

**Comment by jung-kurt** [comment]
You have identified gofpdf's principal shortcoming. Since it is a fairly straightforward port of [fpdf](http://www.fpdf.org/), it inherits that legacy project's use of code page fonts. The practical limitation is that you will be restricted to fewer than 256 glyphs per font, in particular the ones that you have a map for. This regrettably excludes languages with more than that many glyphs.

I would definitely like to support Unicode fonts directly, but for now you need to jump through some hoops. Here is an example that use code page 1251, one that supports Cyrillic:

		cd makefont
		go build
		cd ../font
		# Copy from wherever
		cp /usr/share/fonts/truetype/dejavu/DejaVuSansCondensed.ttf \
		DejaVuSansCondensed-1251.ttf
		./makefont/makefont --embed --enc=cp1251.map DejaVuSansCondensed-1251.ttf

This should produce DejaVuSansCondensed-1251.json and DejaVuSansCondensed-1251.z. In your go code, you can then do something like this:

		pdf := gofpdf.New("P", "mm", "A4", "/path/to/font")
		pdf.AddFont("DejaVuSansCondensed-1251", "", "DejaVuSansCondensed-1251.json")
		fontSize := 16.0
		pdf.SetFont("DejaVuSansCondensed-1251", "", fontSize) // Match name from AddFont()
		// Make the appropriate code page translator
		tr := pdf.UnicodeTranslatorFromDescriptor("cp1251")
		str := tr("Съешь же ещё этих мягких французских булок, да выпей чаю.")

**Comment by korya** [comment]
Thanks for the detailed answer.

I have a legacy PHP code using tcpdf for PDF generation. Since the core of our application is written in golang, I looked for a good candidate to replace tcpdf, so I can port the PHP code to golang. gofpdf looks as a perfect candidate, it's simple, straightforward and its API is similar to tcpf's one (at least for the functionality needed by us). The only problem with gofpdf is that it lacks the unicode support, which is crucial for us. I don't have much time now, so I'm going to leave the idea of porting it to golang, and I'm going to integrate the legacy PHP code into the golang app.

Anyway, do you think it is a big project to bring the unicode support to gofpdf?

**Comment by jung-kurt** [comment]
There are at least two issues that tcpdf must have solved (I haven't examined that library).

*  Change all occurrences of 256-element code page arrays to maps keyed by glyph name or code point
*  Find a way to embed only the used glyphs, since including full Unicode fonts would result in unacceptably large PDFs

It would be nice to support the newer font formats (svg, woof, eot) in addition to otf and ttf.

Any insights appreciated!

**Comment by foresmac** [comment]
This is a modified version of FPDF that supports Unicode fonts, including subsetting. Maybe it provides a direction? http://www.fpdf.org/en/script/script92.php

**Comment by jung-kurt** [comment]
Thanks for link -- I will investigate that.

**Comment by vtirta** [comment]
Just to clarify, does this code:
```
pdf := gofpdf.New("P", "mm", "A4", "/path/to/font")
    pdf.AddFont("DejaVuSansCondensed-1251", "", "DejaVuSansCondensed-1251.json")
    fontSize := 16.0
    pdf.SetFont("DejaVuSansCondensed-1251", "", fontSize) // Match name from AddFont()
    // Make the appropriate code page translator
    tr := pdf.UnicodeTranslatorFromDescriptor("cp1251")
    str := tr("Съешь же ещё этих мягких французских булок, да выпей чаю.")
```
work for Chinese, Korean, or Japanese fonts?

**Comment by jung-kurt** [comment]
@vtirta 

> Just to clarify, does this code ... work for Chinese, Korean, or Japanese fonts?

How I wish it did. However, for reasons explained in previous comments, gofpdf currently only supports fonts that have a code page, that is, ones that have 256 or fewer glyphs. This is gofpdf's biggest shortcoming.
