### ISSUE TITLE
would be cool to use releases and semantic versioning

### ISSUE THREAD

**Issue by dfuentes77** [jung-kurt/gofpdf#111]
This is so that when using a dependency manager, we can lock to a version and get predictable builds

Otherwise, we're sticking to a commit sha or always pulling master.

For example, using glide, we can set to only pull certain patch/minor versions based on our comfort.

**Comment by jung-kurt** [comment]
Thanks for the nudge in this direction, @dfuentes77 -- it's high time to start using [semantic versioning](http://semver.org/) in this project.

Some questions. As [described here](https://stackoverflow.com/questions/18506508/whats-the-difference-between-tag-and-release) Github supports _releases_ on top of git's _tags_. Which of these is used by tools like glide? When does it make sense to tag a commit, and when to release a tag? For example, I can see keeping the tag updated according to the semantic versioning rules but only releasing when the minor version (new functionality) is incremented. Does it make sense to start this process at 1.0.0?

**Comment by marcusatbang** [comment]
A tag is supposed to be a permanent marker. Once you've told git that 

   **tag 1.3.0** = **commit 839ff058bf36f67607808523c245be38b8870b71**

that tag should never change. That tag will forever point to that exact commit. You _can_ change a tag if you really really need to, but you should try to avoid it, not least because it makes things awkward for anybody else with the repo checked out. Branches move; tags don't.

It's more common, if a release needs to be amended, to release subsequent tags like **1.3.0-r2**

Most tools like Glide will speak git, but not know about releases which are specific to GitHub.

> Does it make sense to start this process at 1.0.0?

I'd say the project is easily mature enough to justify calling it 1.0.0 now. Numbering is up to the project maintainer; I've known a project jump from 0.8 to 9.0 :smiley:

**Comment by jung-kurt** [comment]
Thanks, @marcusatbang. I think I'll just stick with tags then and not fuss with releases. 1.0.0 it is.

**Comment by jung-kurt** [comment]
OK, one more question. [This article on tagging](https://git-scm.com/book/en/v2/Git-Basics-Tagging) shows the convention of prefixing the version numbers with the letter 'v', for example 'v1.2.3'. Is that something that should be done here?

**Comment by marcusatbang** [comment]
I think that's common, but not strictly required. Starting with 'v' avoids ambiguity when you've got commit refs starting with numbers. Again, it's up to you what you choose as long as you're consistent.

**Comment by jung-kurt** [comment]
Done. Thanks, all.

**Comment by dfuentes77** [comment]
@jung-kurt Very cool. Much appreciated!
