### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by hiendv** [jung-kurt/gofpdf#125]
Is it possible to implement a table of contents with gofpdf? I was thinking of links and a page showing them and their page number respectively. The problem is the table of contents cannot be placed in first pages since the links are added afterward. Any solutions?

**Comment by jung-kurt** [comment]
The original FPDF site has this [table of contents script](http://www.fpdf.org/en/script/script73.php) that wouldn't be hard to include in gofpdf. The key feature is that it demonstrates how to insert pages at an arbitrary location after other pages have been written. The example table of contents does not show page links, just plain text, but I think links would be possible. 

I am unable to delve into this right now, but in the weeks ahead I will try to find time to explore this further.

**Comment by hiendv** [comment]
The `pages` property is accessible in the PHP script. Is it possible in gofpdf?
```php
//store toc pages
for($i = $tocstart;$i <= $n;$i++)
    $last[]=$this->pages[$i];

//move pages
for($i=$tocstart-1;$i>=$location-1;$i--)
    $this->pages[$i+$n_toc]=$this->pages[$i];

//Put toc pages at insert point
for($i = 0;$i < $n_toc;$i++)
    $this->pages[$location + $i]=$last[$i];
```

**Comment by jung-kurt** [comment]
My preference is to keep the `pages` slice private and to add the table of contents feature right into the gofpdf code. Alternatively, we could add an API that shifts a group of pages to another location.

**Comment by dsfish** [comment]
I'm facing a similar problem and would be happy to submit a PR to address this. The PDF I'm writing has a table of contents that shows the page number where subsequent sections begin.

@jung-kurt, I agree that keeping `pages` private is preferable. My local workaround is to surface a `RegisterAlias` function on the `Fpdf` struct, as follows:

```
func (f *Fpdf) RegisterAlias(alias, replacement string) {
	f.aliasMap[alias] = replacement
}
```

In my table of contents, I write the alias instead of the page number (as is currently done with `aliasNbPagesStr`). When I encounter the beginning of a section that I want to reference in the table of contents, I call `RegisterAlias`, like so:

```
pageNumberAlias := "{0}" // for example
pageNo := strconv.Itoa(pdf.PageNo())
pdf.RegisterAlias(pageNumberAlias, pageNo)
```

Then, using this map of aliases and replacement strings, I'm able to do a global find-and-replace in `putpages`, as is currently done to support `aliasNbPagesStr`.

I also considered making the `RegisterAlias` function more specialized, so that it automatically maps the alias to the current page number.

What do you think of this approach?

**Comment by jung-kurt** [comment]
@dsfish -- I like your proposal and would welcome the PR.

Calling `pdf.RegisterAlias()` can be done anytime before `pdf.Close()` (which indirectly calls `putpages()`), correct? This would allow aliases to be made with information that isn't known until the document is ready to be output.

**Comment by dsfish** [comment]
Thanks for the quick reply! Yep, that's the idea. Do you think I should make it more specialized, per my comment above, so that the `replacement` string is automatically `pdf.PageNo()`, or do you think people will find other use cases for a generic find-and-replace function?

**Comment by jung-kurt** [comment]
I think people will find the generic find-and-replace functionality useful. To handle the page number case automatically, you could prepopulate the map with a special alias and document it.
