### ISSUE TITLE
Generate directly in disk

### ISSUE THREAD

**Issue by giorgiootto** [jung-kurt/gofpdf#137]
Hi, How could generate directly in disk not in memory?????

**Comment by jung-kurt** [comment]
gofpdf always uses memory to build up  document; this can't be changed. (Specifically, it uses a [bytes.Buffer](https://golang.org/pkg/bytes/#Buffer) during construction.)

But if you're interested in writing the document to disk rather than to a generalized io.Writer, a shortcut is [OutputFileAndClose()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.OutputFileAndClose).
