### ISSUE TITLE
Use some cp1250 characters without embedding TTF?

### ISSUE THREAD

**Issue by mileusna** [jung-kurt/gofpdf#140]
I know, UTF-8 not supported. But I only need few extended latin chars like šđčćž ŠĐČĆŽ (can be found in cp1250) and the only way to add this is to embed TTF which increases PDF size from 50K to 200K? Can I just change default code page of PDF document somehow?

I can see that this FPDF version supports UTF-8 characters while creating PDFs of just 15-20Kb http://www.fpdf.org/en/script/script92.php

Can anything be done about this?!

**Comment by jung-kurt** [comment]
> Can I just change default code page of PDF document somehow?

This is a good question. Even though there isn't a method to change the default code page, it wouldn't be difficult to add. What I don't know at this point is what code pages are certain to be supported by PDF readers, so I don't know off hand whether introducing this method would allow invalid documents to be produced. Anyone out there that knows more about this?

> I can see that this FPDF version supports UTF-8 characters while creating PDFs of just 15-20Kb 

It would be nice for gofpdf to embed font subsets. Since this reaches into practically every part of the code base, the question is whether it makes more sense to implement the gofpdf API on top of [gopdf](https://github.com/signintech/gopdf), a package that supports unicode from the ground up.

**Comment by mileusna** [comment]
I will check the situation with [gopdf](https://github.com/signintech/gopdf) can it solve my problem to produce simple and small PDFs with my Latin characters.

**Comment by mileusna** [comment]
Looks like that  [gopdf](https://github.com/signintech/gopdf) will do the trick, thanks for the reference.

**Comment by jung-kurt** [comment]
Good!
