### ISSUE TITLE
FPDF conditional Headers and Footers

### ISSUE THREAD

**Issue by eurosoll** [jung-kurt/gofpdf#149]
I have recently moved from PHP to Go. I had written a complete editor to design PDF documents using fpdf in native PHP.

The fact that the mapping of funcs from PHP to Go in fpdf is a great help to me.

The problem I am facing is conditional headers and footers. In PHP I had a lot of logic whether to display them on first/last pages or to have different headers on different headers on first and then subsequent pages.

An example would be a multiple page invoice where on the first page it displays logos, addresses etc. On following pages it just displays a continuation message.

I notice you have done something similar with footers so that sub totals could be placed in the final page footer.

I am new to Go so I could be missing the point completely, but any help would be very much appreciated.

**Comment by jung-kurt** [comment]
This [example](https://godoc.org/github.com/jung-kurt/gofpdf#example-Fpdf-AddPage) demonstrates headers and footers. In each case, an anonymous function (more specifically, a *closure* because it accesses local variables declared in its parent's scope) is passed to the [SetHeaderFunc](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.SetHeaderFunc) and [SetFooterFunc](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.SetFooterFunc) methods. These functions are called whenever the library is starting or ending a page, respectively. In order to implement different kinds of headers and footers based on location in the document, use the [PageNo]() method, for example in a switch block:

    page := pdf.PageNo() 
    switch {
    case page == 1:
        pdf.Image(...)
    case page > 1:
        pdf.Cell(...)
    }

If you need to have a footer that is different on the last page, use [SetFooterFuncLpi](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.SetFooterFuncLpi) instead of `SetFooterFunc`.

**Comment by eurosoll** [comment]
Thank you. I appreciate the help.
