### ISSUE TITLE
Render PDFs to bitmaps?

### ISSUE THREAD

**Issue by foresmac** [jung-kurt/gofpdf#2]
It doesn't appear that gofpdf includes FPDF's ability to render a PDF file to a bitmap. Am I missing something in that regard? I'm looking for something to open a PDF file, grab the first page, and generate a PNG it (via `image.png.Encode()`).

**Comment by foresmac** [comment]
I think the confusion is that FPDF is similar in name to the FPDFSDK from Foxit. Google has an open source version written in C++: https://pdfium.googlesource.com/pdfium

**Comment by foresmac** [comment]
So maybe I'm barking up the wrong tree?

**Comment by jung-kurt** [comment]
This project writes PDFs only. It is not capable of opening and processing PDF files that already exist. As far as I know, its parent project, [FPDF](http://www.fpdf.org/), is not related to the Foxit PDF SDK (fpdfsdk) despite the name confusion.

I can't see gofpdf ever having the capability of opening PDFs and parsing them. However, the idea of generating an image as output rather than a PDF is intriguing and worth looking into. 

Also, a Go wrapper (using cgo) of the [pdfium](https://pdfium.googlesource.com/pdfium) library could be useful. Thanks for that link.

**Comment by foresmac** [comment]
@jung-kurt Cool. After searching for a few days, I don't see anything native in Go that does what I need, so I'm going to end up using a web-based API from Datalogics. However, if you consider building a wrapper for PDFium, do let me know; I'm more than happy to contribute however I can.

Since we have an internal project that could use this functionality at work, I may be able to use some "20% time" to work on it.

Thanks again.

**Comment by jung-kurt** [comment]
Many thanks!

**Comment by foresmac** [comment]
Have you made any progress to build a Go wrapper around PDFium?

**Comment by jung-kurt** [comment]
I have not had time to work on embedding PDFium. However, if your objective is to generate images or PDFs from vector graphics, you may want to look into [draw2d](https://github.com/llgcode/draw2d).
