### ISSUE TITLE
How to add watarmark to pdf ?

### ISSUE THREAD

**Issue by zsspj12** [jung-kurt/gofpdf#240]
As title, In your  fpdf_test.go , I can't find a function to add watermark to pdf ?

**Comment by jung-kurt** [comment]
To make a watermark that repeats on each page, use the [`SetHeaderFunc()`](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.SetHeaderFunc) method. This lets you draw anywhere on the page as long as you reset the X and Y values before leaving the header function so that normal content begins where expected. 

Adding a watermark to a document is demonstrated in the [TransformRotate example](https://github.com/jung-kurt/gofpdf/blob/8fd1e0a49c50a568249b877054a6401de1c118a8/fpdf_test.go#L2480-L2519).

**Comment by zsspj12** [comment]
3q, @jung-kurt , tomorrow let me have a try。

**Comment by zsspj12** [comment]
pdf.SetHeaderFunc() can add watermark，thank u。

**Comment by zsspj12** [comment]
I had read issues/8，all my problem has resolved. but I still expect other contributor can finish read a pdf file as a template function.
Best wish to gofpdf.

**Comment by jung-kurt** [comment]
Please reopen if this is still an issue.
