### ISSUE TITLE
how to align the lower boundry of two adjacent multicells

### ISSUE THREAD

**Issue by sify21** [jung-kurt/gofpdf#302]
I want two multicells placed next to each other, and I know which one contains more content. I can align the upper boundry with setXY, but **how do I align the lower boundry**?

**Comment by jung-kurt** [comment]
Good question, @sify21. The bottom of a [MultiCell()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.MultiCell) is determined by the number of lines in the content, so you may have to resort to a kluge in which you add a number of blank lines to pad the smaller one. This is admittedly error-prone because you may not know how many wrapped lines the content will have. This is a definite shortcoming of the MultiCell method.

**Comment by sify21** [comment]
Thanks for the reply. Finally I managed to do this using `SplitText`(for caculating max row num) and `CellFormat` to achieve the effects of using `MultiCell`.

**Comment by jung-kurt** [comment]
Good solution.
