### ISSUE TITLE
Problem to générate PDF

### ISSUE THREAD

**Issue by ronron76** [jung-kurt/gofpdf#6]
Hello,
    I used "code.google.com/p/gofpdf" but it is not easy for accent char. Your package is in philosophy of Golang. For generate PDF, all text est in UTF-8.

But I see several problems in this package:
* When I use accent char in CellFormat like "é", the char don't display correctly.
For correct this problem I had add this line "txtStr=utf8toutf16(txtStr)"  in the "fpdf.go" ( ligne 1712 ). I can't insert this line before because GetStringWidth return 0 in utf16.

* Then the text don't display correctly: 
I have delete this line "res = append(res, 0xFE, 0xFF)" in the utf8toutf16 function because I don't be in the beginning file.

Can you check if the correction is good for you ?

**Comment by ghigt** [comment]
You also can do that:
```
tr := pdf.UnicodeTranslatorFromDescriptor("")
pdf.Cell(40, 40, tr("le français c'est compliqué !"))
```

**Comment by marcusatbang** [comment]
I think this is one case where gofpdf should diverge from the original FPDF library, because the two languages have such different takes on character sets.

PDF significatly predates Unicode. I can't claim 

PHP doesn't, strictly speaking, have strings at all. It has blobs which just happen to get treated as strings. It's entirely possible for that blob to contain bytes that don't count as valid UTF-8, or to contain characters in a different encoding, or just to contain the contents of an image file. String were originally assumed to be ASCII, but have since by convention been upgraded to propably-UTF8-ish. There are two sets of string functions, the old set and the new multibyte-aware set, but since the new set has a different name and are slower they aren't often used. In this context, it makes sense for FPDF to put the burden of encodings onto the user of the library.

Go has a proper string type with unicode support baked in from the start. Of course it's possible to trick it into putting invalid bytes into a string variable, but a lot harder. In this context it makes sense instead for gofpdf to assume any string it receives is properly encoded UTF-8, and take care of the correct encoding for you.

**Comment by jung-kurt** [comment]
Excellent remarks. I agree, getting rid of code pages is worth far more than compatibility with FPDF. A baby step to make things a little easier would be to automatically handle the translation to the code page of the currently loaded font. But that does little to bring us closer to using UTF-8 natively. It does not address CJK fonts.

I'm quite certain that the right approach is to embed only the font glyphs that are actually used in the document. But I'm not sure of the best way to go about this. Should a new embedded font be created that comprises these glyphs? Ideas (and code samples!) are appreciated.

**Comment by jung-kurt** [comment]
I'll close this issue since it is stated as an objective in the documentation.

**Comment by leandrorichard** [comment]
@ghigt Thanks!

**Comment by rahulkarmore** [comment]
is there any option to generate pdf in other languages except English in Golang.

**Comment by jung-kurt** [comment]
See [this example](https://godoc.org/github.com/jung-kurt/gofpdf#example-Fpdf-AddUTF8Font).
