### ISSUE TITLE
Add support to read images and fonts from memory (using either an io.Reader or []byte)

### ISSUE THREAD

**Issue by kestred** [jung-kurt/gofpdf#76]
This issue is a feature request to allow Fonts and Images to be added to a PDF from some in-memory representation (for example using either an `io.Reader` or a `[]byte`).

In my use case, pdfs will contain both images and embedded fonts, but they may not be on the filesystem (for example, they may be either included as a `const [...]byte` in the executable, or read from a network stream).

After glancing through the code, it looks like fonts load files in multiple places (reading the `.json` file immediately when defining the font; then reading the compressed `.z` file much later when generating the PDF), so it didn't seem trivial to remove the dependency on the file-system.

If you like the feature idea, and have an idea about how you would go about implementing it, I'd be happy to do the dirty work following a description of the necessary changes.

**Comment by jung-kurt** [comment]
Thanks for your offer to help with this, @kestred 

In fact, images and fonts can be loaded from arbitrary places by means of an io.Reader. However, the documentation is admittedly less than crystal clear. To load an image through a Reader, see [RegisterImageOptionsReader](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.RegisterImageOptionsReader). An example of its use is [here](https://godoc.org/github.com/jung-kurt/gofpdf#example-Fpdf-RegisterImageReader). (The example uses the RegisterImageReader method, but the idea is the same.) To load a font (both the compressed .z file and its .json descriptor file) through an io.Reader, see the [SetFontLoader](https://godoc.org/github.com/jung-kurt/gofpdf#example-Fpdf-SetFontLoader) example.

I think things have gotten a little messy because support for these functions needed to be backwards compatible with the original fpdf code base. Perhaps a useful project would be to write a wrapper that simplifies loading a .ttf font directly through a Reader. That would wrap the functionality of SetFontLoader() with the code in [makefont/makefont.go](https://github.com/jung-kurt/gofpdf/blob/master/makefont/makefont.go) and would check to see if the requested font was already registered.

**Comment by kestred** [comment]
Thanks @jung-kurt!  I didn't notice that I could override the file reading behavior in those ways.

I'll look in to making it easy to use MakeFont at runtime; but first I'll get it working in my code with the existing tools so I have a good test case.

**Comment by jung-kurt** [comment]
Good. I'll close the issue and look forward to a pull request at some point.

Thanks!
