### ISSUE TITLE
Recommendations needed: Copying TIFF image to PDF structure / Writing a layer on the TIFF image 

### ISSUE THREAD

**Issue by dtrehas** [jung-kurt/gofpdf#88]
Dear Members of gofpdf,

Thank you for this wonderful project.

I would like to make a simplistic TIFF2PDF. I used to have it in java and I miss it. I can *not* though execute a command line util in the working environment.

I would like to know that if 
i would be able to read the TIFF structure in someway (dimensions, meta, CCIT-6 compressed ) 
what I should do from _fpdf side_ to copy it in the FPDF structure?

Thank you in advance!

**Comment by jung-kurt** [comment]
Thanks, @dtrehas. My preferred way of supporting TIFFs would be as a separate package in the contrib directory. This is because Go's standard library doesn't support the format and I am reluctant to make gofpdf dependent on non-standard packages. Most likely you could use the Go supplementary package [tiff](https://github.com/golang/image/tree/master/tiff) to generate a [gofpdf.ImageInfoType](https://godoc.org/github.com/jung-kurt/gofpdf#ImageInfoType) structure. I am not familiar with the TIFF format so I am not sure whether this would be straightforward or not. In [fpdf.go](https://github.com/jung-kurt/gofpdf/blob/master/fpdf.go) we could then add a method to register an ImageInfoType structure directly, bypassing the usual png/gif/jpg methods.

Do you have any experience with the [tiff](https://github.com/golang/image/tree/master/tiff) package?

**Comment by dtrehas** [comment]
Not really.. but I tried a bit a few years ago.

I found that there is https://github.com/pascaldekloe/got.6 library that can not be compiled.
 It was from the original tiff package that used to be released with GO long time go.

I could try to modify it a bit.

**Comment by jung-kurt** [comment]
I just added support for standard TIFF images in gofpdf documents. See [tiff](https://github.com/jung-kurt/gofpdf/tree/master/contrib/tiff).
